---
{{- with .Values.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ $.Values.app_name }}
  labels:
    app: {{ $.Values.app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.app_name }}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: {{ $.Values.app_name }}
          image: "{{ .image.name }}:{{ .image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .port }}
{{- end }}
