# ---
# {{- with .Values.app }}
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   namespace: {{ $.Values.namespace }}
#   name: "{{ .name }}"
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#   - host: "{{ .endpoint }}"
#     http:
#       paths:
#       - backend:
#           service:
#             name: "{{ .name }}"
#             port:
#               number: {{ .port }}
#         path: /
#         pathType: ImplementationSpecific
# {{- end }}
