name: Test deployment
# This just runs the build step, without deploying, so you know that your PR will at least build
# Will it look good ? You need to deploy to know...

# Review gh actions docs if you want to further define triggers, paths, etc
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
on:
  pull_request:
    branches:
      - main

env:
  DTT_DOCS_URL: ${{ vars.DTT_DOCS_URL }}
  DTT_DOCS_BASE_PATH: ${{ vars.DTT_DOCS_BASE_PATH }}
  DTT_DOCS_EXCLUDED_PATH: ${{ vars.DTT_DOCS_EXCLUDED_PATH }}
  ORGANIZATION_NAME: ${{ github.repository_owner }}
  PROJECT_NAME: ${{ github.event.repository.name }}

jobs:
  test-build:
    name: Test building the documentation static web site with docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Remove excluded PATHs for build
        run: .github/workflows/excluded-paths.sh

      - name: Test build website
        # When running this test in a PR from the staging to the production repository,
        # vars.* variables are not made avaiable to the action !?!
        # c.f: see https://github.com/orgs/community/discussions/44322
        # We are thus faking those by sourcing .env.sample file
        # thus using hopefully harmless staging values
        #
        # We also create the CNAME file, which is useless in staging,
        # but required in production.
        # It is created temporarily in the static/ folder, and docusaurus will
        # copy it to the /build directory
        run: |
          if [ -z "$DTT_DOCS_URL" ] || [ -z "DTT_DOCS_BASE_PATH" ]; then
            source .env.sample
          fi
          echo "$DTT_DOCS_URL" | cut -f 3 -d/ | tee static/CNAME
          npm run build